import {
  BookMarked,
  User,
  Search,
  Library,
  Star,
  Sparkles,
  Clock,
  Award,
  Briefcase,
  ShieldCheck,
  Crown,
  Cpu,
  HelpCircle,
  LayoutDashboard,
  FileCheck2,
  BookOpen,
} from 'lucide-react';

export const NAVIGATION_ITEMS = [
  {
    path: '/dashboard',
    label: 'Tableau de Bord Filière',
    icon: LayoutDashboard,
    isPrimary: true,
    description: 'Espace étudiant cloisonné par filière et niveau',
  },
  {
    path: '/exams',
    label: 'Compositions en Ligne',
    icon: FileCheck2,
    description: 'Évaluations chronométrées, autosave et relevés notés',
  },
  {
    path: '/ressources',
    label: 'Ressources Nationales',
    icon: Library,
    description: 'Gestion & catalogue des cours (CRUD multi-universités)',
  },
  {
    path: '/tech-hub',
    label: 'Pôle Info & Tech',
    icon: Cpu,
    isTechCore: true,
    description: 'Playground C/Py/SQL, algorithmes et annales nationales',
  },
  {
    path: '/falsh-hub',
    label: 'Pôle FALSH & Lettres',
    icon: BookOpen,
    description: 'Méthodologie dissertation, figures de style & normes APA/MLA',
  },
  {
    path: '/search',
    label: 'Recherche',
    icon: Search,
    description: 'Filtres avancés par filière et niveau',
  },
  {
    path: '/learning',
    label: 'Apprentissage',
    icon: Sparkles,
    description: 'Flashcards, Playground C/Py, IA Résumés & Dico Tech',
  },
  {
    path: '/productivity',
    label: 'Productivité',
    icon: Clock,
    description: 'Pomodoro de groupe, Tableau blanc, iCal & Hors-ligne',
  },
  {
    path: '/evaluation',
    label: 'Évaluation',
    icon: Award,
    description: 'Notes, avis, badges de mérite & anti-plagiat',
  },
  {
    path: '/services',
    label: 'Services & Campus',
    icon: Briefcase,
    description: 'Petites annonces, stages, covoiturage & bibliographie',
  },
  {
    path: '/pricing',
    label: 'CampusHub Pro',
    icon: Crown,
    description: 'Offres Pro, paiements sécurisés & Mobile Money',
  },
  {
    path: '/delegate',
    label: 'Espace Délégué',
    icon: Award,
    requiredRole: 'delegate',
    description: 'Avis officiels, calendrier de classe et coordination amphi',
  },
  {
    path: '/moderation',
    label: 'Console Modération',
    icon: ShieldCheck,
    requiredRole: 'moderator',
    description: 'Signalements, audit anti-plagiat et conformité',
  },
  {
    path: '/admin',
    label: 'Administration',
    icon: Crown,
    requiredRole: 'admin',
    description: 'Gestion des comptes, modération & statistiques UY1',
  },
  {
    path: '/help',
    label: 'Centre d\'Aide & FAQ',
    icon: HelpCircle,
    description: 'FAQ, guide d\'accueil et tickets de support',
  },
  {
    path: '/favs-history',
    aliases: ['/favorites'],
    label: 'Favoris & Historique',
    icon: Star,
    badgeKey: 'favoritesCount',
    description: 'Cours enregistrés et consultations',
  },
  {
    path: '/notebook',
    label: 'Carnet Privé',
    icon: BookMarked,
    description: 'Brouillons et notes personnelles',
  },
  {
    path: '/profile',
    label: 'Profil',
    icon: User,
    description: 'Informations étudiantes et badges',
  },
];

export const PUBLIC_ROUTES = [
  { path: '/login', label: 'Connexion' },
  { path: '/register', label: 'Inscription' },
];
