/**
 * Academic Portal Constants
 * Centralized configuration for disciplines, study levels, storage keys and defaults.
 */

export const STORAGE_KEYS = {
  RESOURCES: 'academic_resources',
  FAVORITES: 'academic_favorites',
  HISTORY: 'academic_history',
  NOTES: 'academic_notes',
  AUTH_USER: 'academic_user',
  THEME: 'theme',
};

export const ACADEMIC_FACULTIES = [
  { id: 'Informatique', label: 'Informatique', code: 'INFO', color: '#6366f1' },
  { id: 'Mathématiques', label: 'Mathématiques', code: 'MATH', color: '#0ea5e9' },
  { id: 'Physique', label: 'Physique', code: 'PHYS', color: '#f59e0b' },
  { id: 'Chimie', label: 'Chimie', code: 'CHIM', color: '#10b981' },
  { id: 'Biologie', label: 'Biologie', code: 'BIO', color: '#ec4899' },
];

export const ACADEMIC_LEVELS = [
  { id: 'L1', label: 'Licence 1 (L1)' },
  { id: 'L2', label: 'Licence 2 (L2)' },
  { id: 'L3', label: 'Licence 3 (L3)' },
  { id: 'M1', label: 'Master 1 (M1)' },
  { id: 'M2', label: 'Master 2 (M2)' },
];

export const DOCUMENT_TYPES = [
  { id: 'all', label: 'Tous les types' },
  { id: 'cours', label: 'Cours Magistraux' },
  { id: 'td', label: 'TD & Travaux Pratiques' },
  { id: 'annales', label: 'Annales d\'Examens' },
  { id: 'fiche', label: 'Fiches de Synthèse' },
];

export const DEFAULT_USER = {
  id: 'usr_uy1_001',
  nom: 'Kenmoe Fotsing',
  email: 'kenmoe@etudiant.univ-yaounde1.cm',
  filiere: 'Informatique',
  niveau: 'L2',
  matricule: '21U2458',
  bio: "Étudiant en Licence 2 Informatique à l'Université de Yaoundé I. Passionné par l'algorithmique, le génie logiciel et les systèmes distribués.",
  avatar: null,
  badges: ['🚀 Pionnier CampusHub', '💻 Développeur Python/C', '📚 Contributeur Certifié'],
  stats: {
    contributions: 14,
    downloads: 48,
    favoritesCount: 6,
  },
};

export const DEFAULT_RESOURCES = [
  {
    id: 1,
    titre: 'Algorithmique & Structures de Données Avancées',
    filiere: 'Informatique',
    niveau: 'L2',
    typeDoc: 'cours',
    description: 'Pointeurs, listes chaînées, arbres binaires équilibrés (AVL, ABR) et analyse de complexité temporelle.',
    enseignant: 'Dr. T. Mbarga',
    codeUe: 'INF201',
    pages: 42,
    downloads: 148,
    format: 'PDF',
    updatedAt: '2026-03-15',
  },
  {
    id: 2,
    titre: 'Annales & Corrigés Analyse Réelle & Séries',
    filiere: 'Mathématiques',
    niveau: 'L1',
    typeDoc: 'annales',
    description: 'Séries entières, intégrales impropres de Riemann, développements limités et annales corrigées de partiels.',
    enseignant: 'Pr. E. Nguemo',
    codeUe: 'MAT101',
    pages: 64,
    downloads: 112,
    format: 'PDF',
    updatedAt: '2026-02-28',
  },
  {
    id: 3,
    titre: 'Électromagnétisme & Lois Fondamentales de Maxwell',
    filiere: 'Physique',
    niveau: 'L2',
    typeDoc: 'cours',
    description: 'Champs électrostatiques, induction magnétique, équations de Maxwell dans le vide et en milieu diélectrique.',
    enseignant: 'Dr. C. Fotso',
    codeUe: 'PHY203',
    pages: 56,
    downloads: 89,
    format: 'PDF',
    updatedAt: '2026-01-20',
  },
  {
    id: 4,
    titre: 'Bases de Données & Systèmes Relationnels (SGBD SQL)',
    filiere: 'Informatique',
    niveau: 'L2',
    typeDoc: 'cours',
    description: 'Modélisation entité-association, normalisation (3NF, BCNF), requêtes SQL complexes et transactions ACID.',
    enseignant: 'Dr. P. Nde',
    codeUe: 'INF204',
    pages: 38,
    downloads: 165,
    format: 'PDF',
    updatedAt: '2026-03-02',
  },
  {
    id: 5,
    titre: 'Travaux Pratiques Programmation Système UNIX & C',
    filiere: 'Informatique',
    niveau: 'L2',
    typeDoc: 'td',
    description: 'Appels systèmes Linux (fork, exec, pipe), gestion des signaux POSIX et programmation concurrente multithread (pthread).',
    enseignant: 'Dr. J. Mballa',
    codeUe: 'INF206',
    pages: 28,
    downloads: 94,
    format: 'PDF',
    updatedAt: '2026-03-10',
  },
  {
    id: 6,
    titre: 'Algèbre Linéaire & Espaces Vectoriels',
    filiere: 'Mathématiques',
    niveau: 'L2',
    typeDoc: 'cours',
    description: 'Réduction des endomorphismes, diagonalisation, trigonalisation et applications aux systèmes différentiels linéaires.',
    enseignant: 'Pr. A. Tientcheu',
    codeUe: 'MAT202',
    pages: 52,
    downloads: 78,
    format: 'PDF',
    updatedAt: '2026-02-14',
  },
  {
    id: 7,
    titre: 'Thermodynamique & Mécanique des Fluides',
    filiere: 'Physique',
    niveau: 'L1',
    typeDoc: 'cours',
    description: 'Premier et second principes de la thermodynamique, cycles thermiques (Carnot), statique et dynamique des fluides parfaits.',
    enseignant: 'Dr. R. Kenne',
    codeUe: 'PHY102',
    pages: 46,
    downloads: 63,
    format: 'PDF',
    updatedAt: '2026-01-18',
  },
  {
    id: 8,
    titre: 'Chimie Organique : Réactions & Mécanismes Réactionnels',
    filiere: 'Chimie',
    niveau: 'L1',
    typeDoc: 'cours',
    description: 'Stéréochimie, énantiomérie, substitutions nucléophiles (SN1, SN2), éliminations (E1, E2) et synthèses aliphatiques.',
    enseignant: 'Dr. M. Biya',
    codeUe: 'CHM101',
    pages: 49,
    downloads: 54,
    format: 'PDF',
    updatedAt: '2026-02-05',
  },
  {
    id: 9,
    titre: 'Biologie Moléculaire & Génétique Générale',
    filiere: 'Biologie',
    niveau: 'L2',
    typeDoc: 'cours',
    description: 'Structure de l\'ADN/ARN, réplication, transcription, traduction du code génétique et régulation de l\'expression génique.',
    enseignant: 'Pr. S. Eyenga',
    codeUe: 'BIO201',
    pages: 60,
    downloads: 71,
    format: 'PDF',
    updatedAt: '2026-02-22',
  },
  {
    id: 10,
    titre: 'Architectures Logicielles & Génie Logiciel Distribué',
    filiere: 'Informatique',
    niveau: 'L3',
    typeDoc: 'cours',
    description: 'Patrons de conception (Design Patterns GoF), architectures micro-services, APIs RESTful et conteneurisation Docker.',
    enseignant: 'Dr. T. Mbarga',
    codeUe: 'INF305',
    pages: 58,
    downloads: 130,
    format: 'PDF',
    updatedAt: '2026-03-12',
  },
  {
    id: 11,
    titre: 'Fiche de Révision : Formulaire d\'Analyse & Dérivées Usuelles',
    filiere: 'Mathématiques',
    niveau: 'L1',
    typeDoc: 'fiche',
    description: 'Mémo récapitulatif ultra-condensé : dérivées usuelles, primitives indispensables et formules de trigonométrie hyperbolique.',
    enseignant: 'Pr. E. Nguemo',
    codeUe: 'MAT101',
    pages: 4,
    downloads: 210,
    format: 'PDF',
    updatedAt: '2026-03-01',
  },
  {
    id: 12,
    titre: 'Intelligence Artificielle & Apprentissage Automatique (Machine Learning)',
    filiere: 'Informatique',
    niveau: 'M1',
    typeDoc: 'cours',
    description: 'Algorithmes supervisés et non-supervisés (régression, SVM, forêts aléatoires), réseaux de neurones profonds et PyTorch.',
    enseignant: 'Dr. F. Djoko',
    codeUe: 'INF402',
    pages: 75,
    downloads: 155,
    format: 'PDF',
    updatedAt: '2026-03-20',
  }
];

export const DEFAULT_NOTES = [
  {
    id: 1,
    title: 'Rappels Complexité Algorithmique',
    content: 'O(1) < O(log n) < O(n) < O(n log n) < O(n^2). Rappel : Quicksort au pire des cas en O(n^2), MergeSort garanti en O(n log n).',
    createdAt: '2026-03-20',
  },
  {
    id: 2,
    title: 'Préparation Examen Systèmes',
    content: 'Revoir les sémaphores de Dijkstra, les conditions de deadlock (Coffman) et l\'algorithme du banquier.',
    createdAt: '2026-03-24',
  },
];
