/**
 * Base de Données Pédagogique Étendue & Cloisonnée par Filière et par Niveau
 * CampusHub - Université de Yaoundé I (UY1)
 *
 * Règle d'or : Étanchéité absolue entre filières et entre niveaux (L1, L2, L3, M1, M2).
 */

export const ACADEMIC_LEVELS_LIST = ['L1', 'L2', 'L3', 'M1', 'M2'];

/**
 * Catalogue complet des cours par filière et par niveau
 */
export const SCOPED_COURSES_CATALOG = [
  // ==========================================
  // INFORMATIQUE
  // ==========================================
  {
    id: 'inf-l1-101',
    codeUe: 'INF101',
    titre: 'Algorithmique & Initiation au Langage C',
    filiere: 'Informatique',
    filiereId: 'Informatique',
    faculty: 'FS',
    niveau: 'L1',
    semestre: 'Semestre 1',
    credits: 6,
    enseignant: 'Dr. P. Kamgue',
    description: 'Bases de l\'algorithmique, types scalaires, structures conditionnelles, boucles et manipulation des tableaux 1D/2D en C.',
    totalMaterials: 8,
    activeExams: 1,
  },
  {
    id: 'inf-l1-102',
    codeUe: 'INF102',
    titre: 'Architecture des Ordinateurs & Systèmes Numériques',
    filiere: 'Informatique',
    filiereId: 'Informatique',
    faculty: 'FS',
    niveau: 'L1',
    semestre: 'Semestre 2',
    credits: 5,
    enseignant: 'Dr. C. Fotso',
    description: 'Algèbre de Boole, portes logiques, circuits combinatoires et séquentiels, registres CPU et représentation mémoire.',
    totalMaterials: 5,
    activeExams: 1,
  },
  {
    id: 'inf-l2-201',
    codeUe: 'INF201',
    titre: 'Algorithmique & Structures de Données Avancées',
    filiere: 'Informatique',
    filiereId: 'Informatique',
    faculty: 'FS',
    niveau: 'L2',
    semestre: 'Semestre 3',
    credits: 6,
    enseignant: 'Dr. T. Mbarga',
    description: 'Pointeurs C, allocation dynamique malloc/free, listes chaînées, arbres binaires de recherche (ABR), arbres AVL et graphes.',
    totalMaterials: 9,
    activeExams: 1,
  },
  {
    id: 'inf-l2-203',
    codeUe: 'INF203',
    titre: 'Systèmes d\'Exploitation & Programmation Système POSIX',
    filiere: 'Informatique',
    filiereId: 'Informatique',
    faculty: 'FS',
    niveau: 'L2',
    semestre: 'Semestre 4',
    credits: 5,
    enseignant: 'Pr. F. Nkenlifack',
    description: 'Gestion des processus (fork/exec/wait), threads POSIX, exclusion mutuelle (mutex/sémaphores de Dijkstra) et tubes IPC.',
    totalMaterials: 7,
    activeExams: 1,
  },
  {
    id: 'inf-l3-301',
    codeUe: 'INF301',
    titre: 'Bases de Données Relationnelles & Optimisation SQL',
    filiere: 'Informatique',
    filiereId: 'Informatique',
    faculty: 'FS',
    niveau: 'L3',
    semestre: 'Semestre 5',
    credits: 6,
    enseignant: 'Dr. M. Tchoupé',
    description: 'Modèle relationnel, normalisation (3NF/BCNF), algèbre relationnelle, index B-Tree, transactions ACID et requêtes SQL complexes.',
    totalMaterials: 8,
    activeExams: 1,
  },
  {
    id: 'inf-l3-302',
    codeUe: 'INF302',
    titre: 'Génie Logiciel : Conception UML & Design Patterns',
    filiere: 'Informatique',
    filiereId: 'Informatique',
    faculty: 'FS',
    niveau: 'L3',
    semestre: 'Semestre 6',
    credits: 5,
    enseignant: 'Pr. J. Kamga',
    description: 'Conception orientée objet UML 2.0, patrons GoF (Singleton, Factory, Observer), tests unitaires et intégration continue CI/CD.',
    totalMaterials: 6,
    activeExams: 1,
  },
  {
    id: 'inf-m1-401',
    codeUe: 'INF401',
    titre: 'Systèmes Distribués, Consensus & Microservices gRPC',
    filiere: 'Informatique',
    filiereId: 'Informatique',
    faculty: 'FS',
    niveau: 'M1',
    semestre: 'Semestre 7',
    credits: 6,
    enseignant: 'Pr. E. Monkam',
    description: 'Algorithmes de consensus distribué (Raft, Paxos), réplication d\'état, communication haute performance RPC gRPC et conteneurisation.',
    totalMaterials: 7,
    activeExams: 1,
  },
  {
    id: 'inf-m2-501',
    codeUe: 'INF501',
    titre: 'Architectures Cloud Haute Disponibilité & Cyber-Résilience',
    filiere: 'Informatique',
    filiereId: 'Informatique',
    faculty: 'FS',
    niveau: 'M2',
    semestre: 'Semestre 9',
    credits: 6,
    enseignant: 'Pr. E. Monkam',
    description: 'Orchestration Kubernetes, architectures multi-régions, sécurité zéro confiance et projet de fin d\'études (PFE).',
    totalMaterials: 5,
    activeExams: 1,
  },

  // ==========================================
  // CHIMIE
  // ==========================================
  {
    id: 'chm-l1-101',
    codeUe: 'CHM101',
    titre: 'Structure de la Matière & Thermodynamique Chimique',
    filiere: 'Chimie',
    filiereId: 'Chimie',
    faculty: 'FS',
    niveau: 'L1',
    semestre: 'Semestre 1',
    credits: 6,
    enseignant: 'Dr. M. Biya',
    description: 'Modèle atomique de Bohr/Schrödinger, liaisons chimiques, états de la matière, premier et second principes de la thermodynamique chimique.',
    totalMaterials: 6,
    activeExams: 1,
  },
  {
    id: 'chm-l2-201',
    codeUe: 'CHM201',
    titre: 'Chimie Organique II : Mécanismes Réactionnels (SN, E, Additions)',
    filiere: 'Chimie',
    filiereId: 'Chimie',
    faculty: 'FS',
    niveau: 'L2',
    semestre: 'Semestre 3',
    credits: 6,
    enseignant: 'Pr. A. Nono',
    description: 'Stéréochimie R/S, substitutions nucléophiles (SN1, SN2), éliminations (E1, E2), réactifs de Grignard et synthèse d\'alcools.',
    totalMaterials: 7,
    activeExams: 1,
  },
  {
    id: 'chm-l3-301',
    codeUe: 'CHM301',
    titre: 'Spectrométrie RMN ¹H/¹³C & Cristallographie X',
    filiere: 'Chimie',
    filiereId: 'Chimie',
    faculty: 'FS',
    niveau: 'L3',
    semestre: 'Semestre 5',
    credits: 6,
    enseignant: 'Dr. E. Mbassi',
    description: 'Élucidation structurale de molécules organiques par RMN 1D/2D, spectrométrie de masse (EI/ESI) et diffraction des rayons X sur poudre.',
    totalMaterials: 6,
    activeExams: 1,
  },
  {
    id: 'chm-m1-401',
    codeUe: 'CHM401',
    titre: 'Synthèse Asymétrique & Catalyse Énantiomérique Avancée',
    filiere: 'Chimie',
    filiereId: 'Chimie',
    faculty: 'FS',
    niveau: 'M1',
    semestre: 'Semestre 7',
    credits: 6,
    enseignant: 'Pr. H. Boyom',
    description: 'Auxiliaires chiraux d\'Evans, hydrogénation asymétrique de Noyori, époxydation de Sharpless et synthèse totale de produits naturels.',
    totalMaterials: 5,
    activeExams: 1,
  },
  {
    id: 'chm-m2-501',
    codeUe: 'CHM501',
    titre: 'Chimie des Matériaux Avancés, Nanomatériaux & Polymères',
    filiere: 'Chimie',
    filiereId: 'Chimie',
    faculty: 'FS',
    niveau: 'M2',
    semestre: 'Semestre 9',
    credits: 6,
    enseignant: 'Pr. F. Tchinda',
    description: 'Polymères conducteurs, nanostructures de carbone, zéolithes, catalyse hétérogène industrielle et formulation verte.',
    totalMaterials: 4,
    activeExams: 1,
  },

  // ==========================================
  // PHYSIQUE
  // ==========================================
  {
    id: 'phy-l1-101',
    codeUe: 'PHY101',
    titre: 'Mécanique du Point Matériel & Cinématique Newtonienne',
    filiere: 'Physique',
    filiereId: 'Physique',
    faculty: 'FS',
    niveau: 'L1',
    semestre: 'Semestre 1',
    credits: 6,
    enseignant: 'Dr. P. Tsafack',
    description: 'Lois de Newton, quantité de mouvement, théorème de l\'énergie cinétique, oscillateur harmonique et forces centrales.',
    totalMaterials: 6,
    activeExams: 1,
  },
  {
    id: 'phy-l2-201',
    codeUe: 'PHY201',
    titre: 'Électromagnétisme & Propagation dans les Milieux Diélectriques',
    filiere: 'Physique',
    filiereId: 'Physique',
    faculty: 'FS',
    niveau: 'L2',
    semestre: 'Semestre 3',
    credits: 6,
    enseignant: 'Dr. E. Nana',
    description: 'Équations de Maxwell sous forme locale et intégrale, vecteur de Poynting, ondes guidées et cavités résonnantes.',
    totalMaterials: 7,
    activeExams: 1,
  },
  {
    id: 'phy-l3-301',
    codeUe: 'PHY301',
    titre: 'Mécanique Quantique Fondamentale & Équation de Schrödinger',
    filiere: 'Physique',
    filiereId: 'Physique',
    faculty: 'FS',
    niveau: 'L3',
    semestre: 'Semestre 5',
    credits: 6,
    enseignant: 'Pr. J. Mvogo',
    description: 'Dualité onde-corpuscule, postulats quantiques, puits de potentiel fini/infini, effet tunnel et atome d\'hydrogène.',
    totalMaterials: 6,
    activeExams: 1,
  },
  {
    id: 'phy-m1-401',
    codeUe: 'PHY401',
    titre: 'Physique des Solides, Semi-conducteurs & Optoélectronique',
    filiere: 'Physique',
    filiereId: 'Physique',
    faculty: 'FS',
    niveau: 'M1',
    semestre: 'Semestre 7',
    credits: 6,
    enseignant: 'Dr. G. Kenfack',
    description: 'Théorie des bandes d\'énergie (Kronig-Penney), transport de porteurs dans les jonctions p-n, diodes lasers et cellules photovoltaïques.',
    totalMaterials: 5,
    activeExams: 1,
  },
  {
    id: 'phy-m2-501',
    codeUe: 'PHY501',
    titre: 'Physique Nucléaire, Particules Élémentaires & Relativité Générale',
    filiere: 'Physique',
    filiereId: 'Physique',
    faculty: 'FS',
    niveau: 'M2',
    semestre: 'Semestre 9',
    credits: 6,
    enseignant: 'Pr. C. Fotso',
    description: 'Modèle en couches du noyau, réactions de fission/fusion, modèle standard des particules et courbure de l\'espace-temps.',
    totalMaterials: 4,
    activeExams: 1,
  },

  // ==========================================
  // MATHÉMATIQUES
  // ==========================================
  {
    id: 'mat-l1-101',
    codeUe: 'MAT101',
    titre: 'Algèbre Linéaire I : Espaces Vectoriels & Systèmes Linéaires',
    filiere: 'Mathématiques',
    filiereId: 'Mathématiques',
    faculty: 'FS',
    niveau: 'L1',
    semestre: 'Semestre 1',
    credits: 6,
    enseignant: 'Dr. G. Fotsing',
    description: 'Sous-espaces vectoriels, bases, dimension, pivot de Gauss, applications linéaires et calcul matriciel.',
    totalMaterials: 7,
    activeExams: 1,
  },
  {
    id: 'mat-l2-201',
    codeUe: 'MAT201',
    titre: 'Analyse II : Séries Numériques & Intégrales Multiples',
    filiere: 'Mathématiques',
    filiereId: 'Mathématiques',
    faculty: 'FS',
    niveau: 'L2',
    semestre: 'Semestre 3',
    credits: 6,
    enseignant: 'Pr. J. Nguemo',
    description: 'Critères de convergence (D\'Alembert, Cauchy), séries de Fourier, intégrales doubles/triples et théorèmes de Green-Riemann.',
    totalMaterials: 7,
    activeExams: 1,
  },
  {
    id: 'mat-l3-301',
    codeUe: 'MAT301',
    titre: 'Topologie Générale, Espaces Métriques & Espaces de Hilbert',
    filiere: 'Mathématiques',
    filiereId: 'Mathématiques',
    faculty: 'FS',
    niveau: 'L3',
    semestre: 'Semestre 5',
    credits: 6,
    enseignant: 'Pr. H. Nzengue',
    description: 'Ouverts, fermés, compacité (Heine-Borel), complétude, théorème du point fixe de Banach et projections orthogonales.',
    totalMaterials: 6,
    activeExams: 1,
  },
  {
    id: 'mat-m1-401',
    codeUe: 'MAT401',
    titre: 'Théorie de la Mesure & Intégration de Lebesgue dans L^p',
    filiere: 'Mathématiques',
    filiereId: 'Mathématiques',
    faculty: 'FS',
    niveau: 'M1',
    semestre: 'Semestre 7',
    credits: 6,
    enseignant: 'Pr. P. Njock',
    description: 'Tribus boréliennes, mesures de Lebesgue, lemme de Fatou, théorème de convergence dominée et dualité L^p-L^q.',
    totalMaterials: 5,
    activeExams: 1,
  },
  {
    id: 'mat-m2-501',
    codeUe: 'MAT501',
    titre: 'Équations aux Dérivées Partielles & Analyse Numérique Avancée',
    filiere: 'Mathématiques',
    filiereId: 'Mathématiques',
    faculty: 'FS',
    niveau: 'M2',
    semestre: 'Semestre 9',
    credits: 6,
    enseignant: 'Pr. S. Talla',
    description: 'Formulation variationnelle, méthode des éléments finis, espaces de Sobolev et modélisation de diffusion.',
    totalMaterials: 5,
    activeExams: 1,
  },

  // ==========================================
  // FALSH - LETTRES MODERNES FRANÇAISES
  // ==========================================
  {
    id: 'lmf-l1-101',
    codeUe: 'LMF101',
    titre: 'Initiation aux Genres Littéraires (Roman, Théâtre, Poésie)',
    filiere: 'Lettres modernes françaises',
    filiereId: 'Lettres modernes françaises',
    faculty: 'FALSH',
    niveau: 'L1',
    semestre: 'Semestre 1',
    credits: 6,
    enseignant: 'Pr. M. Vounda Etoa',
    description: 'Typologie des genres littéraires, versification poétique, dramaturgie classique et théories de la narration textuelle.',
    totalMaterials: 6,
    activeExams: 1,
  },
  {
    id: 'lmf-l2-201',
    codeUe: 'LMF201',
    titre: 'Poétique & Évolution du Roman Négro-Africain',
    filiere: 'Lettres modernes françaises',
    filiereId: 'Lettres modernes françaises',
    faculty: 'FALSH',
    niveau: 'L2',
    semestre: 'Semestre 3',
    credits: 6,
    enseignant: 'Dr. C. Mengue',
    description: 'Des romans de la contestation coloniale (Oyono, Beti, Achebe) aux écritures postcoloniales de la désillusion et de l\'exil.',
    totalMaterials: 7,
    activeExams: 1,
  },
  {
    id: 'lmf-l3-301',
    codeUe: 'LMF301',
    titre: 'Théories Critiques & Stylistique Avancée',
    filiere: 'Lettres modernes françaises',
    filiereId: 'Lettres modernes françaises',
    faculty: 'FALSH',
    niveau: 'L3',
    semestre: 'Semestre 5',
    credits: 6,
    enseignant: 'Pr. A. Mbala',
    description: 'Rhétorique, sémiotique du texte littéraire, structuralisme, figures de style et analyse du discours narratif.',
    totalMaterials: 6,
    activeExams: 1,
  },
  {
    id: 'lmf-m1-401',
    codeUe: 'LMF401',
    titre: 'Littérature Comparée & Études Postcoloniales',
    filiere: 'Lettres modernes françaises',
    filiereId: 'Lettres modernes françaises',
    faculty: 'FALSH',
    niveau: 'M1',
    semestre: 'Semestre 7',
    credits: 6,
    enseignant: 'Pr. V. Etoa',
    description: 'Dialogue des cultures littéraires, théories de l\'hybridation culturelle (Spivak, Bhabha) et francophonies plurielles.',
    totalMaterials: 5,
    activeExams: 1,
  },
  {
    id: 'lmf-m2-501',
    codeUe: 'LMF501',
    titre: 'Séminaire Doctoral & Épistémologie de la Recherche Littéraire',
    filiere: 'Lettres modernes françaises',
    filiereId: 'Lettres modernes françaises',
    faculty: 'FALSH',
    niveau: 'M2',
    semestre: 'Semestre 9',
    credits: 6,
    enseignant: 'Pr. V. Etoa',
    description: 'Méthodologie de la thèse, archivistique littéraire, corpus numériques et humanités digitales.',
    totalMaterials: 4,
    activeExams: 1,
  },

  // ==========================================
  // FALSH - PHILOSOPHIE
  // ==========================================
  {
    id: 'phi-l1-101',
    codeUe: 'PHI101',
    titre: 'Introduction à la Logique Formelle & Syllogistique',
    filiere: 'Philosophie',
    filiereId: 'Philosophie',
    faculty: 'FALSH',
    niveau: 'L1',
    semestre: 'Semestre 1',
    credits: 6,
    enseignant: 'Pr. F. Eboussi',
    description: 'Logique des propositions, tables de vérité, calcul des prédicats, sophismes et syllogismes aristotéliciens.',
    totalMaterials: 6,
    activeExams: 1,
  },
  {
    id: 'phi-l2-201',
    codeUe: 'PHI201',
    titre: 'Philosophie Politique : Contrat Social & Justice',
    filiere: 'Philosophie',
    filiereId: 'Philosophie',
    faculty: 'FALSH',
    niveau: 'L2',
    semestre: 'Semestre 3',
    credits: 6,
    enseignant: 'Dr. L. Njoh',
    description: 'Hobbes, Locke, Rousseau, théorie de la justice de John Rawls et pensée politique africaine contemporaine.',
    totalMaterials: 6,
    activeExams: 1,
  },
  {
    id: 'phi-l3-301',
    codeUe: 'PHI301',
    titre: 'Débats Contemporains de Philosophie Africaine (Towa, Hountondji)',
    filiere: 'Philosophie',
    filiereId: 'Philosophie',
    faculty: 'FALSH',
    niveau: 'L3',
    semestre: 'Semestre 5',
    credits: 6,
    enseignant: 'Pr. E. Boulaga',
    description: 'Critique de l\'ethnophilosophie, modernité critique, herméneutique transculturelle et libération épistémologique.',
    totalMaterials: 7,
    activeExams: 1,
  },
  {
    id: 'phi-m1-401',
    codeUe: 'PHI401',
    titre: 'Épistémologie des Sciences Humaines & Herméneutique',
    filiere: 'Philosophie',
    filiereId: 'Philosophie',
    faculty: 'FALSH',
    niveau: 'M1',
    semestre: 'Semestre 7',
    credits: 6,
    enseignant: 'Pr. J. Ndebi',
    description: 'Réfutabilité de Karl Popper, paradigmes de Thomas Kuhn, herméneutique de Gadamer et Ricoeur.',
    totalMaterials: 5,
    activeExams: 1,
  },
  {
    id: 'phi-m2-501',
    codeUe: 'PHI501',
    titre: 'Bioéthique, Éthique de l\'IA & Philosophie de la Technique',
    filiere: 'Philosophie',
    filiereId: 'Philosophie',
    faculty: 'FALSH',
    niveau: 'M2',
    semestre: 'Semestre 9',
    credits: 6,
    enseignant: 'Pr. J. Ndebi',
    description: 'Responsabilité éthique dans l\'anthropocène, justice algorithmique, transhumanisme et droits des générations futures.',
    totalMaterials: 4,
    activeExams: 1,
  },

  // ==========================================
  // FALSH - HISTOIRE
  // ==========================================
  {
    id: 'his-l1-101',
    codeUe: 'HIS101',
    titre: 'Méthodologie de la Recherche Historique & Sources Orales',
    filiere: 'Histoire',
    filiereId: 'Histoire',
    faculty: 'FALSH',
    niveau: 'L1',
    semestre: 'Semestre 1',
    credits: 6,
    enseignant: 'Pr. D. Abwa',
    description: 'Heuristique des sources, critique interne et externe des documents, tradition orale et mémoire collective en Afrique.',
    totalMaterials: 6,
    activeExams: 1,
  },
  {
    id: 'his-l2-201',
    codeUe: 'HIS201',
    titre: 'Histoire Précoloniale & Grands Royaumes d\'Afrique Centrale',
    filiere: 'Histoire',
    filiereId: 'Histoire',
    faculty: 'FALSH',
    niveau: 'L2',
    semestre: 'Semestre 3',
    credits: 6,
    enseignant: 'Dr. A. Ebanda',
    description: 'Royaume Kongo, empires sahéliens, sultanats du Nord-Cameroun (Rey-Bouba, Adamawa) et chefferies bamiléké.',
    totalMaterials: 7,
    activeExams: 1,
  },
  {
    id: 'his-l3-301',
    codeUe: 'HIS301',
    titre: 'Mouvements Nationalistes & Décolonisation du Cameroun',
    filiere: 'Histoire',
    filiereId: 'Histoire',
    faculty: 'FALSH',
    niveau: 'L3',
    semestre: 'Semestre 5',
    credits: 6,
    enseignant: 'Pr. D. Abwa',
    description: 'L\'UPC de Ruben Um Nyobe, guerres d\'indépendance, tutelle de l\'ONU, réunification de 1961 et construction de l\'État.',
    totalMaterials: 8,
    activeExams: 1,
  },
  {
    id: 'his-m1-401',
    codeUe: 'HIS401',
    titre: 'Histoire Économique de l\'Afrique & Dynamiques Mondiales',
    filiere: 'Histoire',
    filiereId: 'Histoire',
    faculty: 'FALSH',
    niveau: 'M1',
    semestre: 'Semestre 7',
    credits: 6,
    enseignant: 'Pr. V. Ngoh',
    description: 'Traites négrières transatlantique et orientale, économie de traite coloniale et intégration régionale post-indépendance.',
    totalMaterials: 5,
    activeExams: 1,
  },
  {
    id: 'his-m2-501',
    codeUe: 'HIS501',
    titre: 'Archéologie Préhistorique, Muséologie & Gestion du Patrimoine',
    filiere: 'Histoire',
    filiereId: 'Histoire',
    faculty: 'FALSH',
    niveau: 'M2',
    semestre: 'Semestre 9',
    credits: 6,
    enseignant: 'Pr. D. Abwa',
    description: 'Sites mégalithiques de Saa/Tazunu, restitution des biens culturels africains et conservation patrimoniale.',
    totalMaterials: 4,
    activeExams: 1,
  },
];

/**
 * Plannings académiques cloisonnés par filière et niveau
 */
export const SCOPED_CLASS_SCHEDULES = [
  // INFORMATIQUE L1
  {
    id: 'sch-inf-l1',
    filiere: 'Informatique',
    niveau: 'L1',
    amphi: 'Amphi 501 · Campus Principal UY1',
    semestre: 'Semestre 2 (2025-2026)',
    slots: [
      { day: 'Lundi', time: '07h30 - 10h30', ue: 'INF101', type: 'Cours Magistral', prof: 'Dr. P. Kamgue', salle: 'Amphi 501' },
      { day: 'Mardi', time: '13h30 - 16h30', ue: 'INF101', type: 'Travaux Dirigés (TD)', prof: 'M. Tagne', salle: 'Salle B12' },
      { day: 'Mercredi', time: '08h00 - 12h00', ue: 'INF102', type: 'TP Architecture', prof: 'Dr. C. Fotso', salle: 'Labo Info 1' },
      { day: 'Vendredi', time: '10h45 - 13h45', ue: 'INF102', type: 'Cours Magistral', prof: 'Dr. C. Fotso', salle: 'Amphi 501' },
    ],
  },
  // INFORMATIQUE L2
  {
    id: 'sch-inf-l2',
    filiere: 'Informatique',
    niveau: 'L2',
    amphi: 'Amphi 250 · Campus Ngoa-Ekellé UY1',
    semestre: 'Semestre 4 (2025-2026)',
    slots: [
      { day: 'Lundi', time: '08h00 - 11h00', ue: 'INF201', type: 'Cours Magistral (Arbres & Graphes)', prof: 'Dr. T. Mbarga', salle: 'Amphi 250' },
      { day: 'Mercredi', time: '13h30 - 17h30', ue: 'INF203', type: 'TP Programmation C POSIX', prof: 'Pr. F. Nkenlifack', salle: 'Labo Réseaux & Systèmes' },
      { day: 'Jeudi', time: '07h30 - 10h30', ue: 'INF203', type: 'Cours Magistral (Processus/Threads)', prof: 'Pr. F. Nkenlifack', salle: 'Amphi 250' },
      { day: 'Samedi', time: '08h00 - 11h00', ue: 'INF201', type: 'Séance de TD Algorithmique', prof: 'M. Kamga (Délégué)', salle: 'Salle Info 3' },
    ],
  },
  // INFORMATIQUE L3
  {
    id: 'sch-inf-l3',
    filiere: 'Informatique',
    niveau: 'L3',
    amphi: 'Amphi 1001 · Bloc Pédagogique UY1',
    semestre: 'Semestre 6 (2025-2026)',
    slots: [
      { day: 'Mardi', time: '07h30 - 11h30', ue: 'INF301', type: 'Cours & TP Bases de Données SQL', prof: 'Dr. M. Tchoupé', salle: 'Amphi 1001' },
      { day: 'Jeudi', time: '13h00 - 16h00', ue: 'INF302', type: 'Cours Génie Logiciel UML', prof: 'Pr. J. Kamga', salle: 'Amphi 1001' },
      { day: 'Vendredi', time: '08h30 - 12h30', ue: 'INF302', type: 'Projet GoF & Sprint Agile', prof: 'Pr. J. Kamga', salle: 'Labo Génie Logiciel' },
    ],
  },
  // INFORMATIQUE M1
  {
    id: 'sch-inf-m1',
    filiere: 'Informatique',
    niveau: 'M1',
    amphi: 'Salle Séminaire Master · Bâtiment DSI',
    semestre: 'Semestre 8 (2025-2026)',
    slots: [
      { day: 'Lundi', time: '14h00 - 18h00', ue: 'INF401', type: 'Séminaire Systèmes Distribués', prof: 'Pr. E. Monkam', salle: 'Salle DSI-1' },
      { day: 'Mercredi', time: '09h00 - 13h00', ue: 'INF401', type: 'Lab Cluster Kubernetes & Raft', prof: 'Pr. E. Monkam', salle: 'Cloud Lab UY1' },
    ],
  },
  // INFORMATIQUE M2
  {
    id: 'sch-inf-m2',
    filiere: 'Informatique',
    niveau: 'M2',
    amphi: 'Laboratoire Recherche & PFE',
    semestre: 'Semestre 10 (2025-2026)',
    slots: [
      { day: 'Mardi', time: '09h00 - 12h00', ue: 'INF501', type: 'Atelier Architecture & Soutenance PFE', prof: 'Pr. E. Monkam', salle: 'Auditorium Recherche' },
    ],
  },
  // CHIMIE L2
  {
    id: 'sch-chm-l2',
    filiere: 'Chimie',
    niveau: 'L2',
    amphi: 'Amphi 300 · Faculté des Sciences UY1',
    semestre: 'Semestre 4 (2025-2026)',
    slots: [
      { day: 'Lundi', time: '07h30 - 10h30', ue: 'CHM201', type: 'Chimie Organique II', prof: 'Pr. A. Nono', salle: 'Amphi 300' },
      { day: 'Jeudi', time: '13h00 - 17h00', ue: 'CHM201', type: 'TP Synthèse sous Hotte', prof: 'Dr. M. Biya', salle: 'Labo Chimie 2' },
    ],
  },
  // PHYSIQUE L2
  {
    id: 'sch-phy-l2',
    filiere: 'Physique',
    niveau: 'L2',
    amphi: 'Amphi 301 · Faculté des Sciences UY1',
    semestre: 'Semestre 4 (2025-2026)',
    slots: [
      { day: 'Mardi', time: '08h00 - 11h00', ue: 'PHY201', type: 'Électromagnétisme & Maxwell', prof: 'Dr. E. Nana', salle: 'Amphi 301' },
      { day: 'Vendredi', time: '13h30 - 17h30', ue: 'PHY201', type: 'TP Ondes & Oscilloscope', prof: 'Pr. C. Fotso', salle: 'Labo Électronique' },
    ],
  },
  // FALSH - LETTRES MODERNES L1
  {
    id: 'sch-lmf-l1',
    filiere: 'Lettres modernes françaises',
    niveau: 'L1',
    amphi: 'Amphi 700 · FALSH UY1',
    semestre: 'Semestre 2 (2025-2026)',
    slots: [
      { day: 'Lundi', time: '08h00 - 11h00', ue: 'LMF101', type: 'Genres Littéraires & Poétique', prof: 'Pr. M. Vounda Etoa', salle: 'Amphi 700' },
      { day: 'Mercredi', time: '14h00 - 17h00', ue: 'LMF101', type: 'TD Commentaire Composé', prof: 'Dr. C. Mengue', salle: 'Salle Lettres 4' },
    ],
  },
];

/**
 * Tableau d'annonces de classe cloisonnées
 */
export const SCOPED_ANNOUNCEMENTS = [
  {
    id: 'ann-1',
    filiere: 'Informatique',
    niveau: 'L2',
    author: 'Brice Kamga (Délégué INF201/203)',
    authorRole: 'delegate',
    title: 'Rattrapage TP Système C POSIX (Sémaphores & Tubes)',
    date: '2026-03-28',
    priority: 'high',
    content: 'Tous les étudiants de L2 Informatique doivent assister au TP de rattrapage sur les sémaphores POSIX de Dijkstra ce samedi à 08h00 précises au Laboratoire B. Munissez-vous de vos machines avec GCC.',
    pinned: true,
  },
  {
    id: 'ann-2',
    filiere: 'Informatique',
    niveau: 'L2',
    author: 'Prof. F. Nkenlifack',
    authorRole: 'admin',
    title: 'Date du Contrôle Continu INF203 & Dépôt des Mini-projets',
    date: '2026-03-27',
    priority: 'medium',
    content: 'Le contrôle continu théorique aura lieu le mardi 7 avril en Amphi 250. Les mini-projets de simulateur de shell devront être déposés sur CampusHub au plus tard la veille à 23h59.',
    pinned: false,
  },
  {
    id: 'ann-3',
    filiere: 'Informatique',
    niveau: 'L1',
    author: 'Délégué INF101',
    authorRole: 'delegate',
    title: 'Correction de la fiche TD n°4 : Tableaux et Pointeurs de base',
    date: '2026-03-26',
    priority: 'normal',
    content: 'La solution détaillée des exercices sur les matrices et le tri à bulles en C est disponible dans l\'onglet Supports de cours.',
    pinned: false,
  },
  {
    id: 'ann-4',
    filiere: 'Chimie',
    niveau: 'L2',
    author: 'Délégué Chimie L2',
    authorRole: 'delegate',
    title: 'Port de la blouse en coton obligatoire pour le TP de Chimie Organique',
    date: '2026-03-27',
    priority: 'high',
    content: 'Rappel de sécurité de laboratoire : l\'accès aux hottes sera refusé sans lunettes de protection et blouse 100% coton.',
    pinned: true,
  },
  {
    id: 'ann-5',
    filiere: 'Lettres modernes françaises',
    niveau: 'L1',
    author: 'Délégué LMF101',
    authorRole: 'delegate',
    title: 'Atelier Méthodologique : Structuration de la Dissertation Littéraire',
    date: '2026-03-27',
    priority: 'normal',
    content: 'Séance d\'entraînement ce jeudi en Amphi 700 sur la problématisation d\'un sujet autour d\'Aimé Césaire.',
    pinned: true,
  },
];
