/**
 * Academic Portal Constants - National Cameroon Scope
 * Configuration pour toutes les universités scientifiques et techniques du Cameroun
 * avec cœur fort en Informatique & Génie Logiciel.
 */

export const STORAGE_KEYS = {
  RESOURCES: 'academic_resources',
  FAVORITES: 'academic_favorites',
  HISTORY: 'academic_history',
  NOTES: 'academic_notes',
  AUTH_USER: 'academic_user',
  AUTH_TOKEN: 'campushub_auth_token',
  AUTH_SESSION: 'campushub_auth_session',
  THEME: 'theme',
  SELECTED_UNIVERSITY: 'campushub_selected_university',
};

export const CAMEROON_UNIVERSITIES = [
  {
    id: 'UY1',
    code: 'UY1',
    name: 'Université de Yaoundé I',
    shortName: 'Univ. Yaoundé I',
    type: 'Université d\'État',
    city: 'Yaoundé',
    region: 'Centre',
    campuses: ['Ngoa-Ekellé', 'Château', 'Melun'],
    faculties: ['Faculté des Sciences (FS)', 'FALSH', 'FMSB'],
    badgeColor: '#6366f1',
    iconText: 'UY1',
    isFlagship: true,
  },
  {
    id: 'ENSPY',
    code: 'ENSPY',
    name: 'École Nationale Supérieure Polytechnique de Yaoundé',
    shortName: 'Polytechnique Yaoundé',
    type: 'Grande École d\'Ingénieurs',
    city: 'Yaoundé',
    region: 'Centre',
    campuses: ['Melun / Ngoa-Ekellé'],
    faculties: ['Génie Informatique & Télécoms', 'Génie Électrique', 'Génie Mécanique'],
    badgeColor: '#0ea5e9',
    iconText: 'POLY',
    isFlagship: true,
  },
  {
    id: 'UDO',
    code: 'UDO',
    name: 'Université de Douala',
    shortName: 'Univ. Douala',
    type: 'Université d\'État',
    city: 'Douala',
    region: 'Littoral',
    campuses: ['Ange Raphaël', 'Pk17', 'Logbessou'],
    faculties: ['Faculté des Sciences', 'IUT de Douala', 'ENSPD'],
    badgeColor: '#10b981',
    iconText: 'UDO',
    isFlagship: true,
  },
  {
    id: 'ENSPD',
    code: 'ENSPD',
    name: 'École Nationale Supérieure Polytechnique de Douala',
    shortName: 'Polytechnique Douala',
    type: 'Grande École d\'Ingénieurs',
    city: 'Douala',
    region: 'Littoral',
    campuses: ['Ange Raphaël / Logbessou'],
    faculties: ['Technologies de l\'Information', 'Génie Industriel'],
    badgeColor: '#f59e0b',
    iconText: 'ENSPD',
    isFlagship: false,
  },
  {
    id: 'UDS',
    code: 'UDS',
    name: 'Université de Dschang',
    shortName: 'Univ. Dschang',
    type: 'Université d\'État',
    city: 'Dschang',
    region: 'Ouest',
    campuses: ['Campus Principal Dschang', 'IUT Bandjoun'],
    faculties: ['Faculté des Sciences', 'IUT FOTSO Victor (Bandjoun)'],
    badgeColor: '#ec4899',
    iconText: 'UDS',
    isFlagship: false,
  },
  {
    id: 'UB',
    code: 'UB',
    name: 'University of Buea',
    shortName: 'Univ. Buea',
    type: 'Anglo-Saxon State University',
    city: 'Buea',
    region: 'Sud-Ouest',
    campuses: ['Molyko Main Campus'],
    faculties: ['Faculty of Science', 'Faculty of Engineering & Technology (FET)', 'CoT'],
    badgeColor: '#8b5cf6',
    iconText: 'UB',
    isFlagship: false,
  },
  {
    id: 'UBA',
    code: 'UBA',
    name: 'University of Bamenda',
    shortName: 'Univ. Bamenda',
    type: 'Anglo-Saxon State University',
    city: 'Bamenda',
    region: 'Nord-Ouest',
    campuses: ['Bambili Campus'],
    faculties: ['Faculty of Science', 'NAHPI', 'COLTECH'],
    badgeColor: '#14b8a6',
    iconText: 'UBA',
    isFlagship: false,
  },
  {
    id: 'UN',
    code: 'UN',
    name: 'Université de Ngaoundéré',
    shortName: 'Univ. Ngaoundéré',
    type: 'Université d\'État',
    city: 'Ngaoundéré',
    region: 'Adamaoua',
    campuses: ['Dang Campus'],
    faculties: ['Faculté des Sciences', 'IUT de Ngaoundéré', 'ENSAI'],
    badgeColor: '#ef4444',
    iconText: 'UN',
    isFlagship: false,
  },
];

export const ACADEMIC_FACULTIES = [
  // Cœur Fort Tech & Informatique
  { id: 'Informatique', label: 'Informatique & Génie Logiciel', code: 'INFO-GL', color: '#6366f1', isTechCore: true },
  { id: 'IA-Data', label: 'Intelligence Artificielle & Data Science', code: 'IA-DS', color: '#8b5cf6', isTechCore: true },
  { id: 'Cyber-Reseaux', label: 'Systèmes, Réseaux & Cybersécurité', code: 'SRC', color: '#0ea5e9', isTechCore: true },
  // Autres Filières Scientifiques & Pédagogiques
  { id: 'Mathématiques', label: 'Mathématiques & Modélisation', code: 'MATH', color: '#38bdf8', isTechCore: false },
  { id: 'Physique', label: 'Physique, Électronique & Énergie', code: 'PHYS', color: '#f59e0b', isTechCore: false },
  { id: 'Chimie', label: 'Chimie & Sciences des Matériaux', code: 'CHIM', color: '#10b981', isTechCore: false },
  { id: 'Biologie', label: 'Biosciences & Biotechnologies', code: 'BIO', color: '#ec4899', isTechCore: false },
  { id: 'Genie-Civil', label: 'Génie Civil & Environnement', code: 'GC', color: '#f97316', isTechCore: false },
];

export const ACADEMIC_LEVELS = [
  { id: 'L1', label: 'Licence 1 (L1) / Niveau 1' },
  { id: 'L2', label: 'Licence 2 (L2) / Niveau 2' },
  { id: 'L3', label: 'Licence 3 (L3) / Niveau 3' },
  { id: 'M1', label: 'Master 1 (M1) / 4ème Année Ingénieur' },
  { id: 'M2', label: 'Master 2 (M2) / PFE 5ème Année Ingénieur' },
];

export const DOCUMENT_TYPES = [
  { id: 'all', label: 'Tous les types' },
  { id: 'cours', label: 'Cours Magistraux' },
  { id: 'td', label: 'TD & Travaux Pratiques' },
  { id: 'annales', label: 'Annales d\'Examens' },
  { id: 'fiche', label: 'Fiches de Synthèse & Code' },
];

export const DEFAULT_USER = {
  id: 'usr_nat_001',
  nom: 'Yan Fotsing',
  fullName: 'Yan Fotsing',
  email: 'yanfotsing96@gmail.com',
  universityId: 'UY1',
  universityName: 'Université de Yaoundé I',
  filiere: 'Informatique',
  niveau: 'L2',
  matricule: '23S40192',
  status: 'Étudiant Pro',
  nationalId: 'CM-UY1-2026-0492',
  bio: 'Étudiant en Licence 2 Informatique (UY1/Polytechnique). Passionné par le développement système en C, l\'intelligence artificielle et le Cloud.',
  avatar: null,
  role: 'Étudiant',
  isPro: true,
  badges: ['🇨🇲 CampusHub National', '💻 Développeur C/Python', '🚀 Major Algorithmique'],
  stats: {
    contributions: 14,
    downloads: 48,
    favoritesCount: 6,
  },
};

export const DEFAULT_RESOURCES = [
  {
    id: 1,
    titre: 'Algorithmique & Structures de Données Avancées (Arbres & Graphes)',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Informatique',
    niveau: 'L2',
    typeDoc: 'cours',
    description: 'Pointeurs, listes chaînées, arbres binaires équilibrés (AVL, ABR), graphes (Dijkstra) et complexité asymptotique.',
    enseignant: 'Dr. T. Mbarga',
    codeUe: 'INF201',
    pages: 42,
    downloads: 148,
    rating: 4.9,
    format: 'PDF',
    updatedAt: '2026-03-15',
    authorMatricule: '23U1084',
    authorName: 'Brice Kamga (Délégué INF201)',
    authorRole: 'delegate',
  },
  {
    id: 2,
    titre: 'Architecture Matérielle & Programmation Système C (POSIX)',
    universityId: 'ENSPY',
    universityName: 'Polytechnique Yaoundé',
    filiere: 'Informatique',
    niveau: 'L3',
    typeDoc: 'td',
    description: 'Gestion des processus sous Linux (fork, exec), communication IPC (pipes, files de messages) et synchronisation multithread par sémaphores.',
    enseignant: 'Pr. J. Kamga',
    codeUe: 'INFO310',
    pages: 35,
    downloads: 215,
    rating: 4.8,
    format: 'PDF',
    updatedAt: '2026-03-10',
    authorMatricule: '23U1084',
    authorName: 'Brice Kamga (Délégué INF201)',
    authorRole: 'delegate',
  },
  {
    id: 3,
    titre: 'Bases de Données Relationnelles Avancées & Optimisation SQL',
    universityId: 'UDO',
    universityName: 'Université de Douala',
    filiere: 'Informatique',
    niveau: 'L2',
    typeDoc: 'cours',
    description: 'Normalisation (3NF/BCNF), algèbre relationnelle, procédures stockées PL/SQL, index B-Tree et gestion des transactions ACID.',
    enseignant: 'Dr. F. Bilong',
    codeUe: 'INFO204',
    pages: 58,
    downloads: 168,
    rating: 4.7,
    format: 'PDF',
    updatedAt: '2026-02-28',
    authorMatricule: 'ADM-UY1-001',
    authorName: 'Prof. Joseph Nguemo (Super Admin)',
    authorRole: 'admin',
  },
  {
    id: 4,
    titre: 'Annales Corrigées Examen Algèbre Linéaire & Calcul Matriciel',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Mathématiques',
    niveau: 'L1',
    typeDoc: 'annales',
    description: 'Espaces vectoriels, diagonalisation, formes quadratiques et séries de partiels corrigés avec méthode détaillée.',
    enseignant: 'Pr. E. Nguemo',
    codeUe: 'MAT101',
    pages: 64,
    downloads: 189,
    rating: 4.9,
    format: 'PDF',
    updatedAt: '2026-02-28',
    authorMatricule: '23U5021',
    authorName: 'Délégué Mathématiques',
    authorRole: 'delegate',
  },
  {
    id: 5,
    titre: 'Électromagnétisme & Propagation des Ondes Guidées',
    universityId: 'ENSPD',
    universityName: 'Polytechnique Douala',
    filiere: 'Physique',
    niveau: 'L2',
    typeDoc: 'cours',
    description: 'Équations de Maxwell, ondes électromagnétiques planes dans le vide, réflexion et réfraction, guides d\'ondes diélectriques.',
    enseignant: 'Dr. C. Fotso',
    codeUe: 'PHY203',
    pages: 56,
    downloads: 98,
    rating: 4.6,
    format: 'PDF',
    updatedAt: '2026-01-20',
    authorMatricule: '23U6110',
    authorName: 'Délégué Physique',
    authorRole: 'delegate',
  },
  {
    id: 6,
    titre: 'Sécurité Réseaux, Cryptographie RSA & Pare-feu Linux',
    universityId: 'UB',
    universityName: 'University of Buea',
    filiere: 'Cyber-Reseaux',
    niveau: 'M1',
    typeDoc: 'td',
    description: 'Chiffrement asymétrique RSA/ECC, hachage SHA, protocoles SSL/TLS, analyse de paquets Wireshark et règles iptables.',
    enseignant: 'Dr. M. Enow',
    codeUe: 'CEF415',
    pages: 48,
    downloads: 142,
    rating: 4.8,
    format: 'PDF',
    updatedAt: '2026-03-01',
    authorMatricule: '23U7204',
    authorName: 'Délégué Réseaux',
    authorRole: 'delegate',
  },
  {
    id: 7,
    titre: 'Génie Logiciel : Conception UML & Design Patterns GoF',
    universityId: 'UDS',
    universityName: 'Université de Dschang',
    filiere: 'Informatique',
    niveau: 'L3',
    typeDoc: 'cours',
    description: 'Modélisation objet UML 2.0, patrons de conception (Singleton, Factory, Observer, Strategy), architectures logicielles et tests unitaires.',
    enseignant: 'Dr. T. Kenfack',
    codeUe: 'INFO302',
    pages: 62,
    downloads: 174,
    rating: 4.8,
    format: 'PDF',
    updatedAt: '2026-03-12',
    authorMatricule: '23U1084',
    authorName: 'Brice Kamga (Délégué INF201)',
    authorRole: 'delegate',
  },
  {
    id: 8,
    titre: 'Chimie Organique : Mécanismes Réactionnels & Synthèses',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Chimie',
    niveau: 'L1',
    typeDoc: 'cours',
    description: 'Stéréochimie, énantiomérie, substitutions nucléophiles (SN1, SN2), éliminations (E1, E2) et synthèses aliphatiques.',
    enseignant: 'Dr. M. Biya',
    codeUe: 'CHM101',
    pages: 49,
    downloads: 87,
    rating: 4.5,
    format: 'PDF',
    updatedAt: '2026-02-05',
    authorMatricule: '23U8301',
    authorName: 'Délégué Chimie',
    authorRole: 'delegate',
  },
  {
    id: 9,
    titre: 'Biologie Moléculaire & Génétique des Populations',
    universityId: 'UBA',
    universityName: 'University of Bamenda',
    filiere: 'Biologie',
    niveau: 'L2',
    typeDoc: 'cours',
    description: 'Structure de l\'ADN/ARN, réplication, transcription, traduction du code génétique et lois de Hardy-Weinberg.',
    enseignant: 'Pr. S. Eyenga',
    codeUe: 'BIO201',
    pages: 60,
    downloads: 79,
    rating: 4.6,
    format: 'PDF',
    updatedAt: '2026-02-22',
    authorMatricule: 'MOD-FS-042',
    authorName: 'Dr. Sarah Eyenga (Modératrice)',
    authorRole: 'moderator',
  },
  // INFORMATIQUE L1
  {
    id: 10,
    titre: 'Polycopié : Algorithmique Fondamentale & Syntaxe du Langage C ANSI',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Informatique',
    niveau: 'L1',
    typeDoc: 'cours',
    description: 'Types de base, structures conditionnelles if/else/switch, boucles et manipulation des tableaux unidimensionnels et matrices.',
    enseignant: 'Dr. P. Kamgue',
    codeUe: 'INF101',
    pages: 44,
    downloads: 312,
    rating: 4.8,
    format: 'PDF',
    updatedAt: '2026-03-01',
    authorMatricule: '23U1084',
    authorName: 'Brice Kamga (Délégué INF201)',
    authorRole: 'delegate',
  },
  // INFORMATIQUE MASTER
  {
    id: 11,
    titre: 'Architectures Logicielles Microservices, RPC gRPC & Consensus Distribué',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Informatique',
    niveau: 'Master',
    typeDoc: 'cours',
    description: 'Algorithmes Raft et Paxos, réplication d\'état, communication haute performance gRPC et conteneurisation Docker.',
    enseignant: 'Pr. E. Monkam',
    codeUe: 'INF401',
    pages: 58,
    downloads: 185,
    rating: 4.9,
    format: 'PDF',
    updatedAt: '2026-03-12',
    authorMatricule: 'ADM-UY1-001',
    authorName: 'Prof. Joseph Nguemo (Super Admin)',
    authorRole: 'admin',
  },
  // MATHÉMATIQUES L2
  {
    id: 12,
    titre: 'Analyse II : Séries Numériques, Séries Entières & Intégrales Généralisées',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Mathématiques',
    niveau: 'L2',
    typeDoc: 'cours',
    description: 'Critères de convergence (D\'Alembert, Cauchy, Riemann), séries de Fourier et calcul différentiel.',
    enseignant: 'Pr. J. Nguemo',
    codeUe: 'MAT201',
    pages: 52,
    downloads: 140,
    rating: 4.7,
    format: 'PDF',
    updatedAt: '2026-02-20',
    authorMatricule: '23U5021',
    authorName: 'Délégué Mathématiques',
    authorRole: 'delegate',
  },
  // MATHÉMATIQUES L3
  {
    id: 13,
    titre: 'Topologie Générale & Théorie de la Mesure de Lebesgue',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Mathématiques',
    niveau: 'L3',
    typeDoc: 'cours',
    description: 'Espaces métriques complets, théorème du point fixe de Banach, tribus boréliennes et intégration de Lebesgue.',
    enseignant: 'Pr. E. Nguemo',
    codeUe: 'MAT301',
    pages: 66,
    downloads: 128,
    rating: 4.8,
    format: 'PDF',
    updatedAt: '2026-03-05',
    authorMatricule: '23U5021',
    authorName: 'Délégué Mathématiques',
    authorRole: 'delegate',
  },
  // MATHÉMATIQUES MASTER
  {
    id: 14,
    titre: 'Analyse Fonctionnelle, Espaces de Hilbert & Opérateurs Linéaires',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Mathématiques',
    niveau: 'Master',
    typeDoc: 'cours',
    description: 'Théorème de Hahn-Banach, théorème de Riesz, opérateurs compacts et décomposition spectrale.',
    enseignant: 'Pr. S. Talla',
    codeUe: 'MAT401',
    pages: 72,
    downloads: 98,
    rating: 4.9,
    format: 'PDF',
    updatedAt: '2026-03-08',
    authorMatricule: 'ADM-UY1-001',
    authorName: 'Prof. Joseph Nguemo (Super Admin)',
    authorRole: 'admin',
  },
  // PHYSIQUE L1
  {
    id: 15,
    titre: 'Mécanique du Point Matériel & Dynamique Newtonienne',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Physique',
    niveau: 'L1',
    typeDoc: 'cours',
    description: 'Cinématique, lois du mouvement de Newton, théorème de l\'énergie cinétique et oscillateur harmonique simple.',
    enseignant: 'Dr. P. Tsafack',
    codeUe: 'PHY101',
    pages: 45,
    downloads: 215,
    rating: 4.7,
    format: 'PDF',
    updatedAt: '2026-02-15',
    authorMatricule: '23U6110',
    authorName: 'Délégué Physique',
    authorRole: 'delegate',
  },
  // PHYSIQUE L3
  {
    id: 16,
    titre: 'Mécanique Quantique Fondamentale : Postulats & Puits de Potentiel',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Physique',
    niveau: 'L3',
    typeDoc: 'cours',
    description: 'Fonction d\'onde, équation de Schrödinger, opérateurs hermitiques, relations d\'incertitude et effet tunnel.',
    enseignant: 'Pr. J. Mvogo',
    codeUe: 'PHY301',
    pages: 56,
    downloads: 165,
    rating: 4.8,
    format: 'PDF',
    updatedAt: '2026-03-02',
    authorMatricule: '23U6110',
    authorName: 'Délégué Physique',
    authorRole: 'delegate',
  },
  // PHYSIQUE MASTER
  {
    id: 17,
    titre: 'Physique de l\'État Solide, Jonctions Semi-conductrices & Optoélectronique',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Physique',
    niveau: 'Master',
    typeDoc: 'cours',
    description: 'Structure cristalline, théorie des bandes d\'énergie, modèle de Kronig-Penney et physique des composants à semi-conducteurs.',
    enseignant: 'Dr. G. Kenfack',
    codeUe: 'PHY401',
    pages: 64,
    downloads: 135,
    rating: 4.9,
    format: 'PDF',
    updatedAt: '2026-03-10',
    authorMatricule: 'ADM-UY1-001',
    authorName: 'Prof. Joseph Nguemo (Super Admin)',
    authorRole: 'admin',
  },
  // CHIMIE L2
  {
    id: 18,
    titre: 'Chimie Organique II : Mécanismes Réactionnels SN1/SN2, E1/E2 & Stéréochimie',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Chimie',
    niveau: 'L2',
    typeDoc: 'cours',
    description: 'Inversion de Walden, élimination de Zaitsev, réactifs organométalliques de Grignard et synthèse d\'alcools.',
    enseignant: 'Dr. M. Biya',
    codeUe: 'CHM201',
    pages: 54,
    downloads: 130,
    rating: 4.6,
    format: 'PDF',
    updatedAt: '2026-02-18',
    authorMatricule: '23U8301',
    authorName: 'Délégué Chimie',
    authorRole: 'delegate',
  },
  // CHIMIE L3
  {
    id: 19,
    titre: 'Cinétique Chimique Formelle, Catalyse & Électrochimie de Nernst',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Chimie',
    niveau: 'L3',
    typeDoc: 'td',
    description: 'Ordres de réactions, énergie d\'activation d\'Arrhenius, diagrammes de Pourbaix et piles électrochimiques.',
    enseignant: 'Pr. A. Njoya',
    codeUe: 'CHM301',
    pages: 48,
    downloads: 115,
    rating: 4.7,
    format: 'PDF',
    updatedAt: '2026-03-04',
    authorMatricule: '23U8301',
    authorName: 'Délégué Chimie',
    authorRole: 'delegate',
  },
  // CHIMIE MASTER
  {
    id: 20,
    titre: 'Spectrométrie RMN 1H/13C, Spectrométrie de Masse & Cristallographie X',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Chimie',
    niveau: 'Master',
    typeDoc: 'cours',
    description: 'Élucidation structurale de composés organiques complexes, diffraction des rayons X sur monocristal et couplages RMN 2D.',
    enseignant: 'Pr. F. Tchinda',
    codeUe: 'CHM401',
    pages: 70,
    downloads: 110,
    rating: 4.9,
    format: 'PDF',
    updatedAt: '2026-03-11',
    authorMatricule: 'ADM-UY1-001',
    authorName: 'Prof. Joseph Nguemo (Super Admin)',
    authorRole: 'admin',
  },
  // BIOLOGIE L1
  {
    id: 21,
    titre: 'Biologie Cellulaire : Structure des Organites, Membranes & Métabolisme',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Biologie',
    niveau: 'L1',
    typeDoc: 'cours',
    description: 'Structure des cellules eucaryotes et procaryotes, transport membranaire actif/passif, cycle de Krebs et ATP synthétase.',
    enseignant: 'Dr. S. Kuate',
    codeUe: 'BIO101',
    pages: 46,
    downloads: 190,
    rating: 4.7,
    format: 'PDF',
    updatedAt: '2026-02-14',
    authorMatricule: 'MOD-FS-042',
    authorName: 'Dr. Sarah Eyenga (Modératrice)',
    authorRole: 'moderator',
  },
  // BIOLOGIE L3
  {
    id: 22,
    titre: 'Immunologie Cellulaire & Moléculaire : CMH, Lymphocytes T/B & Anticorps',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Biologie',
    niveau: 'L3',
    typeDoc: 'cours',
    description: 'Présentation antigénique par le CMH I et II, commutation isotypique des immunoglobulines et cascade du complément.',
    enseignant: 'Dr. C. Mbida',
    codeUe: 'BIO301',
    pages: 58,
    downloads: 145,
    rating: 4.8,
    format: 'PDF',
    updatedAt: '2026-03-07',
    authorMatricule: 'MOD-FS-042',
    authorName: 'Dr. Sarah Eyenga (Modératrice)',
    authorRole: 'moderator',
  },
  // BIOLOGIE MASTER
  {
    id: 23,
    titre: 'Biotechnologies Moléculaires Avancées & Ingénierie Génomique CRISPR-Cas9',
    universityId: 'UY1',
    universityName: 'Université de Yaoundé I',
    filiere: 'Biologie',
    niveau: 'Master',
    typeDoc: 'cours',
    description: 'Clonage moléculaire, vecteurs d\'expression, ARN guides sgRNA, réparation HDR/NHEJ et applications thérapeutiques.',
    enseignant: 'Pr. H. Nguema',
    codeUe: 'BIO401',
    pages: 68,
    downloads: 125,
    rating: 4.9,
    format: 'PDF',
    updatedAt: '2026-03-14',
    authorMatricule: 'ADM-UY1-001',
    authorName: 'Prof. Joseph Nguemo (Super Admin)',
    authorRole: 'admin',
  },
];

export const DEFAULT_NOTES = [
  {
    id: 1,
    title: 'Rappels Complexité Algorithmique (Grand O)',
    content: 'O(1) < O(log n) < O(n) < O(n log n) < O(n^2). Rappel : Quicksort au pire des cas en O(n^2), MergeSort garanti en O(n log n). Attention aux fuites mémoires en C.',
    createdAt: '2026-03-20',
  },
  {
    id: 2,
    title: 'Préparation Examen Systèmes d\'Exploitation & POSIX',
    content: 'Revoir les sémaphores de Dijkstra, les conditions de deadlock (Coffman : exclusion mutuelle, rétention/attente, non-préemption, attente circulaire) et IPC pipes.',
    createdAt: '2026-03-24',
  },
];
