/**
 * Cloisonnement Académique & Définition Relationnelle des Filières
 * CampusHub Cameroun - Standards Ministère de l'Enseignement Supérieur (MINESUP)
 */

export const DEPARTMENTS = [
  {
    id: 'Informatique',
    code: 'INFO-GL',
    label: 'Informatique & Génie Logiciel',
    labelEn: 'Computer Science & Software Engineering',
    faculty: 'Faculté des Sciences / Polytechnique',
    color: '#6366f1',
    bgColor: 'bg-indigo-50 dark:bg-indigo-950/60',
    borderColor: 'border-indigo-200 dark:border-indigo-800',
    badgeText: 'text-indigo-700 dark:text-indigo-300',
    isTechFlagship: true,
    description: 'Algorithmique, Structures de données, Systèmes d\'exploitation POSIX, Génie Logiciel, C/Python/Java et architectures Cloud.',
  },
  {
    id: 'IA-Data',
    code: 'IA-DS',
    label: 'Intelligence Artificielle & Data Science',
    labelEn: 'Artificial Intelligence & Data Science',
    faculty: 'Faculté des Sciences / ENSPY',
    color: '#8b5cf6',
    bgColor: 'bg-purple-50 dark:bg-purple-950/60',
    borderColor: 'border-purple-200 dark:border-purple-800',
    badgeText: 'text-purple-700 dark:text-purple-300',
    isTechFlagship: true,
    description: 'Machine Learning, Deep Learning, Probabilités & Statistiques, Big Data, Vision par Ordinateur et Traitement du Langage Naturel.',
  },
  {
    id: 'Cyber-Reseaux',
    code: 'SRC',
    label: 'Systèmes, Réseaux & Cybersécurité',
    labelEn: 'Systems, Networks & Cybersecurity',
    faculty: 'Faculté des Sciences / IUT',
    color: '#0ea5e9',
    bgColor: 'bg-sky-50 dark:bg-sky-950/60',
    borderColor: 'border-sky-200 dark:border-sky-800',
    badgeText: 'text-sky-700 dark:text-sky-300',
    isTechFlagship: true,
    description: 'Protocoles TCP/IP, Cryptographie RSA/AES, Pentesting, Sécurité Linux, Pare-feux et Forensics numérique.',
  },
  {
    id: 'Mathématiques',
    code: 'MATH',
    label: 'Mathématiques & Modélisation',
    labelEn: 'Mathematics & Modeling',
    faculty: 'Faculté des Sciences',
    color: '#38bdf8',
    bgColor: 'bg-cyan-50 dark:bg-cyan-950/60',
    borderColor: 'border-cyan-200 dark:border-cyan-800',
    badgeText: 'text-cyan-700 dark:text-cyan-300',
    isTechFlagship: false,
    description: 'Analyse réelle et complexe, Algèbre linéaire, Topologie, Équations Différentielles et Recherche Opérationnelle.',
  },
  {
    id: 'Physique',
    code: 'PHYS',
    label: 'Physique, Électronique & Énergie',
    labelEn: 'Physics & Electronics',
    faculty: 'Faculté des Sciences',
    color: '#f59e0b',
    bgColor: 'bg-amber-50 dark:bg-amber-950/60',
    borderColor: 'border-amber-200 dark:border-amber-800',
    badgeText: 'text-amber-700 dark:text-amber-300',
    isTechFlagship: false,
    description: 'Mécanique quantique, Électromagnétisme, Électronique analogique et numérique, Thermodynamique et Semi-conducteurs.',
  },
  {
    id: 'Chimie',
    code: 'CHIM',
    label: 'Chimie & Sciences des Matériaux',
    labelEn: 'Chemistry & Material Sciences',
    faculty: 'Faculté des Sciences',
    color: '#10b981',
    bgColor: 'bg-emerald-50 dark:bg-emerald-950/60',
    borderColor: 'border-emerald-200 dark:border-emerald-800',
    badgeText: 'text-emerald-700 dark:text-emerald-300',
    isTechFlagship: false,
    description: 'Chimie organique, Cinétique chimique, Spectrométrie, Électrochimie et Cristallographie.',
  },
  {
    id: 'Biologie',
    code: 'BIO',
    label: 'Biosciences & Biotechnologies',
    labelEn: 'Biosciences & Biotechnologies',
    faculty: 'Faculté des Sciences',
    color: '#ec4899',
    bgColor: 'bg-pink-50 dark:bg-pink-950/60',
    borderColor: 'border-pink-200 dark:border-pink-800',
    badgeText: 'text-pink-700 dark:text-pink-300',
    isTechFlagship: false,
    description: 'Génétique moléculaire, Microbiologie, Biochimie métabolique, Écologie et Immunologie.',
  },
  {
    id: 'Genie-Civil',
    code: 'GC',
    label: 'Génie Civil & Environnement',
    labelEn: 'Civil & Environmental Engineering',
    faculty: 'Grandes Écoles d\'Ingénieurs (ENSPY/ENSPD)',
    color: '#f97316',
    bgColor: 'bg-orange-50 dark:bg-orange-950/60',
    borderColor: 'border-orange-200 dark:border-orange-800',
    badgeText: 'text-orange-700 dark:text-orange-300',
    isTechFlagship: false,
    description: 'Résistance des matériaux (RDM), Béton armé, Topographie, Géotechnique et Hydraulique.',
  },
];

export const ACADEMIC_LEVELS = [
  { id: 'L1', shortLabel: 'L1', label: 'Licence 1 / 1ère Année', semester: 'Semestre 1 & 2' },
  { id: 'L2', shortLabel: 'L2', label: 'Licence 2 / 2ème Année', semester: 'Semestre 3 & 4' },
  { id: 'L3', shortLabel: 'L3', label: 'Licence 3 / 3ème Année', semester: 'Semestre 5 & 6' },
  { id: 'M1', shortLabel: 'M1', label: 'Master 1 / 4ème Année Ing.', semester: 'Semestre 7 & 8' },
  { id: 'M2', shortLabel: 'M2', label: 'Master 2 / 5ème Année Ing.', semester: 'Semestre 9 & 10' },
];

/**
 * Catalogue Relationnel des Unités d'Enseignement (UE)
 * Reliées strictement à (filiereId, niveau)
 */
export const RELATION_COURSES = [
  // INFORMATIQUE - L2
  {
    id: 'course-inf201',
    codeUe: 'INF201',
    filiereId: 'Informatique',
    niveau: 'L2',
    titre: 'Algorithmique & Structures de Données Avancées',
    credits: 6,
    enseignant: 'Dr. T. Mbarga',
    semestre: 'Semestre 3',
    description: 'Pointeurs C, allocation dynamique malloc/free, listes chaînées, arbres binaires de recherche (ABR), arbres AVL, tables de hachage et graphes.',
    totalMaterials: 8,
    activeExams: 1,
  },
  {
    id: 'course-inf203',
    codeUe: 'INF203',
    filiereId: 'Informatique',
    niveau: 'L2',
    titre: 'Systèmes d\'Exploitation & Programmation Système POSIX',
    credits: 5,
    enseignant: 'Pr. F. Nkenlifack',
    semestre: 'Semestre 3',
    description: 'Gestion des processus (fork/exec/wait), ordonnancement CPU, threads POSIX, exclusion mutuelle (mutex/sémaphores de Dijkstra) et mémoire virtuelle.',
    totalMaterials: 6,
    activeExams: 1,
  },
  {
    id: 'course-inf205',
    codeUe: 'INF205',
    filiereId: 'Informatique',
    niveau: 'L2',
    titre: 'Architecture des Ordinateurs & Assembleur x86/ARM',
    credits: 4,
    enseignant: 'Dr. C. Fotso',
    semestre: 'Semestre 4',
    description: 'Modèle de Von Neumann, registres CPU, bus de données, jeux d\'instructions RISC/CISC, pipeline et mémoires caches L1/L2/L3.',
    totalMaterials: 5,
    activeExams: 0,
  },

  // INFORMATIQUE - L1
  {
    id: 'course-inf101',
    codeUe: 'INF101',
    filiereId: 'Informatique',
    niveau: 'L1',
    titre: 'Initiation à l\'Algorithmique & Programmation C',
    credits: 6,
    enseignant: 'Dr. P. Kamgue',
    semestre: 'Semestre 1',
    description: 'Variables, types élémentaires, structures conditionnelles (if/switch), boucles (for/while), fonctions et tableaux 1D/2D en C ANSI.',
    totalMaterials: 7,
    activeExams: 1,
  },

  // INFORMATIQUE - L3
  {
    id: 'course-inf301',
    codeUe: 'INF301',
    filiereId: 'Informatique',
    niveau: 'L3',
    titre: 'Bases de Données Relationnelles & SQL Avancé',
    credits: 5,
    enseignant: 'Dr. M. Tchoupé',
    semestre: 'Semestre 5',
    description: 'Modèle entité-association, algèbre relationnelle, normalisation (1FN à BCNF), requêtes SQL complexes, transactions ACID et index B-Tree.',
    totalMaterials: 9,
    activeExams: 1,
  },

  // IA-DATA - L2
  {
    id: 'course-iad201',
    codeUe: 'IAD201',
    filiereId: 'IA-Data',
    niveau: 'L2',
    titre: 'Fondements Mathématiques de l\'Apprentissage Automatique',
    credits: 6,
    enseignant: 'Dr. R. Mvogo',
    semestre: 'Semestre 3',
    description: 'Algèbre linéaire appliquée aux tenseurs, décomposition en valeurs singulières (SVD), optimisation par descente de gradient et régressions.',
    totalMaterials: 5,
    activeExams: 1,
  },

  // CYBER-RÉSEAUX - L2
  {
    id: 'course-sec201',
    codeUe: 'SEC201',
    filiereId: 'Cyber-Reseaux',
    niveau: 'L2',
    titre: 'Architecture des Réseaux Locaux & Modèle OSI/TCP-IP',
    credits: 5,
    enseignant: 'Dr. B. Atangana',
    semestre: 'Semestre 3',
    description: 'Couches physique, liaison, réseau, transport et application. Adressage IPv4/IPv6, sous-réseaux CIDR, VLANs 802.1Q et routage statique.',
    totalMaterials: 6,
    activeExams: 1,
  },

  // MATHÉMATIQUES - L2
  {
    id: 'course-mat201',
    codeUe: 'MAT201',
    filiereId: 'Mathématiques',
    niveau: 'L2',
    titre: 'Analyse II : Séries Numériques & Intégrales Multiples',
    credits: 6,
    enseignant: 'Pr. J. Nguemo',
    semestre: 'Semestre 3',
    description: 'Critères de convergence (D\'Alembert, Cauchy), séries entières et de Fourier, intégrales doubles et triples, théorèmes de Green-Riemann.',
    totalMaterials: 6,
    activeExams: 1,
  },

  // PHYSIQUE - L2
  {
    id: 'course-phy201',
    codeUe: 'PHY201',
    filiereId: 'Physique',
    niveau: 'L2',
    titre: 'Électromagnétisme & Propagation dans les Milieux Diélectriques',
    credits: 5,
    enseignant: 'Dr. E. Nana',
    semestre: 'Semestre 3',
    description: 'Équations de Maxwell sous forme locale et intégrale, vecteur de Poynting, ondes guidées et cavités résonnantes.',
    totalMaterials: 4,
    activeExams: 1,
  },

  // CHIMIE - L1 & L2
  {
    id: 'course-chm101',
    codeUe: 'CHM101',
    filiereId: 'Chimie',
    niveau: 'L1',
    titre: 'Chimie Générale & Solutions Aqueuses',
    credits: 6,
    enseignant: 'Dr. M. Biya',
    semestre: 'Semestre 1',
    description: 'Thermodynamique chimique, équilibres acido-basiques, pH, réactions d\'oxydoréduction et cinétique en solution aqueuse.',
    totalMaterials: 5,
    activeExams: 1,
  },
  {
    id: 'course-chm201',
    codeUe: 'CHM201',
    filiereId: 'Chimie',
    niveau: 'L2',
    titre: 'Chimie Organique Structurale & Réactions de Synthèse',
    credits: 5,
    enseignant: 'Pr. A. Nono',
    semestre: 'Semestre 3',
    description: 'Mécanismes réactionnels SN1/SN2, éliminations E1/E2, stéréochimie R/S et synthèse de molécules aromatiques.',
    totalMaterials: 6,
    activeExams: 0,
  },

  // BIOLOGIE - L1 & L2
  {
    id: 'course-bio101',
    codeUe: 'BIO101',
    filiereId: 'Biologie',
    niveau: 'L1',
    titre: 'Biologie Moléculaire & Génétique Fondamentale',
    credits: 6,
    enseignant: 'Dr. S. Kuate',
    semestre: 'Semestre 1',
    description: 'Structure de l\'ADN, réplication semi-conservative, transcription, code génétique, biosynthèse des protéines et lois de Mendel.',
    totalMaterials: 6,
    activeExams: 1,
  },
  {
    id: 'course-bio201',
    codeUe: 'BIO201',
    filiereId: 'Biologie',
    niveau: 'L2',
    titre: 'Microbiologie Générale & Métabolisme Bactérien',
    credits: 5,
    enseignant: 'Pr. H. Mbiapo',
    semestre: 'Semestre 3',
    description: 'Structure de la paroi bactérienne (Gram+/Gram-), métabolisme aérobie/anaérobie, génétique bactérienne et agents antimicrobiens.',
    totalMaterials: 5,
    activeExams: 0,
  },
];
